In [1]:
import numpy as np

from ase import Atoms
from ase.io import read
from ase.lattice.cubic import Diamond
from ase.lattice.hexagonal import Graphite

import quippy
from quippy.descriptors import Descriptor

# from dscribe.descriptors import SOAP

from soap_package5 import  soap_desc

In [2]:
atoms = Diamond("C")
atoms.set_pbc([False,False,False])

In [3]:
desc_vera = soap_desc(atoms,rcut = 3.7,l_max = 1, n_max = 2,atom_sigma = 0.5)

In [4]:
desc_vera

array([array([ 0.84524512,  0.42374559, -0.13552799, -0.25338436,  0.02173078,
               0.15151458])                                                   ,
       array([ 0.94512803,  0.02228462, -0.30919639, -0.01621438,  0.10115286,
               0.01179765])                                                   ,
       array([ 0.90708287,  0.2740529 , -0.24578702, -0.16509778,  0.06659949,
               0.09995823])                                                   ,
       array([ 0.89081196,  0.336108  , -0.18000528, -0.20718816,  0.03637345,
               0.12974435])                                                   ,
       array([ 0.90708287,  0.2740529 , -0.24578702, -0.16509778,  0.06659949,
               0.09995823])                                                   ,
       array([ 0.89081196,  0.336108  , -0.18000528, -0.20718816,  0.03637345,
               0.12974435])                                                   ,
       array([ 0.90708287,  0.2740529 , -0.245

In [5]:
gap = Descriptor("soap cutoff=3.7 l_max=1 n_max=2 atom_sigma=0.5")
desc_gap = gap.calc(atoms)
desc_gap['data']

array([[9.94627490e-01, 9.35533000e-13, 1.03214779e-01, 1.04593534e-07,
        5.35541734e-03, 5.84683137e-03, 0.00000000e+00],
       [9.94841169e-01, 8.87519038e-13, 1.01162378e-01, 9.92255247e-08,
        5.14344752e-03, 5.54675693e-03, 0.00000000e+00],
       [9.43666135e-01, 9.20572652e-12, 3.21239035e-01, 1.02920952e-06,
        5.46774511e-02, 5.75333319e-02, 0.00000000e+00],
       [9.42143615e-01, 1.10856746e-11, 3.23249527e-01, 1.23938961e-06,
        5.54534655e-02, 6.92825050e-02, 0.00000000e+00],
       [9.43666135e-01, 9.20572652e-12, 3.21239035e-01, 1.02920952e-06,
        5.46774511e-02, 5.75333319e-02, 0.00000000e+00],
       [9.42143615e-01, 1.10856746e-11, 3.23249527e-01, 1.23938961e-06,
        5.54534655e-02, 6.92825050e-02, 0.00000000e+00],
       [9.43666135e-01, 9.20572652e-12, 3.21239035e-01, 1.02920952e-06,
        5.46774511e-02, 5.75333319e-02, 0.00000000e+00],
       [9.42143615e-01, 1.10856746e-11, 3.23249527e-01, 1.23938961e-06,
        5.54534655e-02, 6

In [5]:
dscribe = SOAP(species = ['C'],rcut=3.7, nmax=2, lmax=1, sigma=0.5, rbf='polynomial')
desc_dscribe = dscribe.create(atoms)

for i in range(len(desc_dscribe)):
    desc_dscribe[i]=desc_dscribe[i] / np.linalg.norm(desc_dscribe[i]) #normalisation

array([[2.92859121e-01, 4.90306315e-01, 8.20873469e-01, 6.30721907e-34,
        3.52422127e-34, 1.99491749e-34],
       [1.86191980e-01, 3.90027050e-01, 8.17012096e-01, 3.74286587e-01,
        7.35104723e-02, 1.44375720e-02],
       [1.86191980e-01, 3.90027050e-01, 8.17012096e-01, 3.74286587e-01,
        7.35104723e-02, 1.44375720e-02],
       [1.86191980e-01, 3.90027050e-01, 8.17012096e-01, 3.74286587e-01,
        7.35104723e-02, 1.44375720e-02],
       [1.86191980e-01, 3.90027050e-01, 8.17012096e-01, 3.74286587e-01,
        7.35104723e-02, 1.44375720e-02]])